### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by dleitee** [CheesecakeLabs/front-end-boilerplate#1]
## Tasks (13/06/2019)

  - [ ] @dleitee add server files for dev and prod
  - [ ] @mibsbalsante install and config storybook
  - [ ] @natamvo install and config Jest
  - [ ] @natamvo add some basic tests using Jest
  - [x] @helderburato add .editorconfig file
  - [x] @helderburato config postcss
  - [x] @matbueno install and config stylelint
  - [ ] @salatielq add SVG support
  - [x] @DiegoBousfield config prettier
  - [x] @beatriz1304 add webpack loaders for JS, Images and Files
  - [x] @beatriz1304 add webpack resolvers
  - [x] @alissongranemann add and config Husky for `pre-install`, `pre-commit` and `pre-push`
